language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

# Command to install dependencies

pip install -r requirements.txt

# Command to run tests

script:
    - coverage run tests.py

after_success:
    - codecov